//! The PWA shell (#48): manifest, service worker and icons are served
//! from the binary like the rest of the portal, the worker NEVER caches
//! the hovedbok, and the same receipt sent twice becomes one bilag —
//! because a phone without coverage retries. Requires DATABASE_URL for
//! the upload half (skips that part otherwise).

use crate::common::{TestIdp, test_state, unique_orgnr};
use axum::body::Body;
use axum::http::{Request, StatusCode};
use tower::ServiceExt;
use uuid::Uuid;

use regnmed_api::{AppState, router};

async fn get(state: &AppState, uri: &str) -> (StatusCode, String, String) {
    let response = router(state.clone())
        .oneshot(Request::builder().uri(uri).body(Body::empty()).unwrap())
        .await
        .unwrap();
    let status = response.status();
    let content_type = response
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or_default()
        .to_string();
    let bytes = axum::body::to_bytes(response.into_body(), 1024 * 1024)
        .await
        .unwrap();
    (
        status,
        content_type,
        String::from_utf8_lossy(&bytes).to_string(),
    )
}

#[tokio::test]
async fn the_pwa_shell_is_served_and_never_caches_the_hovedbok() {
    let idp = TestIdp::new();
    let Some(state) = test_state(&idp).await else {
        return;
    };

    let (status, content_type, manifest) = get(&state, "/manifest.webmanifest").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(content_type, "application/manifest+json");
    let manifest: serde_json::Value = serde_json::from_str(&manifest).expect("gyldig JSON");
    assert_eq!(manifest["display"], "standalone");
    assert_eq!(manifest["start_url"], "/");
    let icons = manifest["icons"].as_array().unwrap();
    assert!(
        icons.iter().any(|i| i["purpose"] == "maskable"),
        "Android beskjærer ikonet — det må finnes et maskable"
    );

    // The icons are real PNGs (generated by scripts/build-icons.py).
    for (path, forventet_bredde) in [("/icon-192.png", 192u32), ("/icon-512.png", 512)] {
        let response = router(state.clone())
            .oneshot(Request::builder().uri(path).body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK, "{path}");
        assert_eq!(
            response.headers().get("content-type").unwrap(),
            "image/png",
            "{path}"
        );
        let bytes = axum::body::to_bytes(response.into_body(), 1024 * 1024)
            .await
            .unwrap();
        assert_eq!(&bytes[..8], b"\x89PNG\r\n\x1a\n", "{path} er en PNG");
        let bredde = u32::from_be_bytes([bytes[16], bytes[17], bytes[18], bytes[19]]);
        assert_eq!(bredde, forventet_bredde, "{path}");
    }

    let (status, content_type, sw) = get(&state, "/sw.js").await;
    assert_eq!(status, StatusCode::OK);
    assert!(content_type.starts_with("text/javascript"));
    // The rule that matters: only the shell is cached. The shell is now
    // the Vite build, so the rule is expressed as addresses (/assets/ +
    // the fixed PWA files) instead of a list of file names.
    assert!(
        sw.contains("SHELL_FILES") && sw.contains("/assets/") && !sw.contains("/companies/"),
        "arbeideren må aldri lagre noe fra hovedboken"
    );
    assert!(
        sw.contains("request.method !== \"GET\""),
        "endrende forespørsler går aldri gjennom cachen"
    );

    // index.html points at the manifest, or nothing is installable.
    let (_, _, index) = get(&state, "/").await;
    assert!(index.contains("rel=\"manifest\""), "{index}");
    assert!(index.contains("apple-touch-icon"), "{index}");
}

#[tokio::test]
async fn the_same_receipt_twice_becomes_one_bilag() {
    let idp = TestIdp::new();
    let Some(state) = test_state(&idp).await else {
        return;
    };
    let sub = format!("test|{}", Uuid::new_v4());
    let person = regnmed_db::ensure_person(&state.pool, &sub, Some("Kari Kvittering"), None)
        .await
        .unwrap();
    let company = regnmed_db::create_company(&state.pool, &unique_orgnr(), "Feltarbeid AS")
        .await
        .unwrap();
    regnmed_db::ensure_company_member(&state.pool, company, person, "admin")
        .await
        .unwrap();
    let token = idp.token(&sub, "Kari Kvittering");
    let bilde = b"JPEG-bytes fra kameraet".to_vec();
    let sha256 = hex::encode(regnmed_core::hash::sha256(&bilde));

    let last_opp = |filnavn: &str, hash: Option<&str>, bytes: Vec<u8>| {
        let state = state.clone();
        let token = token.clone();
        let uri = format!(
            "/companies/{company}/inbox?filename={filnavn}{}",
            hash.map(|h| format!("&sha256={h}")).unwrap_or_default()
        );
        async move {
            let response = router(state)
                .oneshot(
                    Request::builder()
                        .method("POST")
                        .uri(uri)
                        .header("authorization", format!("Bearer {token}"))
                        .header("content-type", "image/jpeg")
                        .body(Body::from(bytes))
                        .unwrap(),
                )
                .await
                .unwrap();
            let status = response.status();
            let bytes = axum::body::to_bytes(response.into_body(), 1024 * 1024)
                .await
                .unwrap();
            let body: serde_json::Value =
                serde_json::from_slice(&bytes).unwrap_or(serde_json::Value::Null);
            (status, body)
        }
    };

    // The phone sends the image with its own hash.
    let (status, body) = last_opp("kvittering.jpg", Some(&sha256), bilde.clone()).await;
    assert_eq!(status, StatusCode::OK, "{body}");

    // The queue retried because the response never arrived. Same content,
    // new file name — and there must still be only one bilag.
    let (status, body) = last_opp("kvittering-2.jpg", Some(&sha256), bilde.clone()).await;
    assert_eq!(status, StatusCode::BAD_REQUEST);
    assert!(
        body["error"].as_str().unwrap().contains("ligger allerede"),
        "{body}"
    );

    // A hash that does not match means the bytes were damaged in transit.
    let (status, body) =
        last_opp("skadet.jpg", Some(&"0".repeat(64)), b"andre bytes".to_vec()).await;
    assert_eq!(status, StatusCode::BAD_REQUEST);
    assert!(body["error"].as_str().unwrap().contains("skadet"), "{body}");

    let documents = regnmed_db::list_inbox(&state.pool, company, None)
        .await
        .unwrap();
    assert_eq!(documents.len(), 1, "ett bilde, ett bilag");
}
